steps:
# Run tests
- name: 'python'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      export PYTHONPATH=/workspace && \
      pip install -r requirements.txt && \
      pytest tests/

# Migrate and deploy the application
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update && \
      apt-get install -y gettext-base && \
      pip install -r requirements.txt && \
      envsubst < env_variables_template.yaml > substituted_env.yaml && \
      cat static_app.yaml substituted_env.yaml > app.yaml && \
      flask db upgrade && \
      flask db stamp head && \
      gcloud app deploy
  env:
    - 'AUTH_SECRET_KEY=$_AUTH_SECRET_KEY'
    - 'FLASK_SECRET_KEY=$_FLASK_SECRET_KEY'
    - 'GOOGLE_CALLBACK_URL=$_GOOGLE_CALLBACK_URL'
    - 'GOOGLE_CLIENT_ID=$_GOOGLE_CLIENT_ID'
    - 'GOOGLE_CLIENT_SECRET=$_GOOGLE_CLIENT_SECRET'
    - 'GOOGLE_BACKEND_PROJECT_ID=$_GOOGLE_BACKEND_PROJECT_ID'
    - 'GOOGLE_SSO_JSON_FILE_PATH=$_GOOGLE_SSO_JSON_FILE_PATH'
    - 'GOOGLE_USER_EMAIL_API=$_GOOGLE_USER_EMAIL_API'
    - 'GOOGLE_USER_PROFILE_API=$_GOOGLE_USER_PROFILE_API'
    - 'POSTGRES_DB_URL=$_POSTGRES_DB_URL'
    - 'REACT_FRONTEND_URL=$_REACT_FRONTEND_URL'

options:
  volumes:
    - name: 'pip-cache'
      path: '/root/.cache/pip'
