steps:
# Start PostgreSQL, run tests, and clean up
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      pip install -r requirements.txt && \
      docker run -d --name postgres-test -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=chefselect_test_db -p 5432:5432 postgres:13 && \
      echo "Waiting for PostgreSQL to be ready..." && \
      until docker exec postgres-test pg_isready -U postgres; do
        sleep 1;
      done && \
      export TEST_POSTGRES_DB_URL=postgresql://postgres:postgres@localhost:5432/chefselect_test_db && \
      export PYTHONPATH=/workspace && \
      pytest tests/ && \
      docker stop postgres-test && \
      docker rm postgres-test

# Migrate and deploy the application
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update && \
      apt-get install -y gettext-base && \
      pip install -r requirements.txt && \
      envsubst < env_variables_template.yaml > substituted_env.yaml && \
      cat static_app.yaml substituted_env.yaml > app.yaml && \
      flask db migrate && \
      flask db upgrade && \
      gcloud app deploy
  env:
    - 'POSTGRES_DB_URL=$_POSTGRES_DB_URL'

options:
  volumes:
    - name: 'pip-cache'
      path: '/root/.cache/pip'
