steps:
# Run tests
- name: 'python'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      export PYTHONPATH=/workspace && \
      pip install -r requirements.txt && \
      pytest tests/

# Migrate and deploy the application
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update && \
      apt-get install -y gettext-base && \
      pip install -r requirements.txt && \
      envsubst < env_variables_template.yaml > substituted_env.yaml && \
      cat static_app.yaml substituted_env.yaml > app.yaml && \
      echo "Checking current.." && \
      flask db current
      echo "Checking history.." && \
      flask db history
      PGPASSWORD='chefselectdb' psql -h chefselectdb@chefselect-db.cl064ik6yj8q.eu-west-1.rds.amazonaws.com -U postgres -d chefselect -c "DROP TABLE IF EXISTS alembic_version;"
      echo "Starting real migration.." && \
      flask db migrate && \
      echo "Migration Success.." && \
      flask db upgrade && \
      flask db stamp head && \\
      gcloud app deploy
  env:
    - 'POSTGRES_DB_URL=$_POSTGRES_DB_URL'

options:
  volumes:
    - name: 'pip-cache'
      path: '/root/.cache/pip'
