steps:
# Install requirements and run migrations
- name: 'python'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cat app.yaml
      pip install -r requirements.txt
      flask db upgrade

# Add testing

# Deploy the application
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cat app.yaml 
      gcloud app deploy
  env:
  - '_POSTGRES_DB_URL=$__POSTGRES_DB_URL' 

options:
  volumes:
    - name: 'pip-cache'
      path: '/root/.cache/pip'

