steps:
# Add testing

# Migrate and deploy the application
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update && \
      apt-get install -y gettext-base && \
      pip install -r requirements.txt && \ 
      envsubst < env_variables_template.yaml > substituted_env.yaml && \
      flask db upgrade && \
      gcloud app deploy
  env:
    - 'POSTGRES_DB_URL=$_POSTGRES_DB_URL'

options:
  volumes:
    - name: 'pip-cache'
      path: '/root/.cache/pip'
