steps:
- name: 'python'
  entrypoint: 'python'
  args: ['-m', 'pip', 'install', '-r', 'requirements.txt']

# Add testing

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud app deploy']