steps:
# Install requirements and run migrations
- name: 'python'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      sed "s/blabla/$_DATABASE_URL/g" app.yaml > tmp_app.yaml && mv tmp_app.yaml app.yaml
      cat app.yaml
      pip install -r requirements.txt
      flask db upgrade

# Add testing

# Deploy the application
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      sed "s/blabla/$_DATABASE_URL/g" app.yaml > tmp_app.yaml && mv tmp_app.yaml app.yaml
      cat app.yaml 
      gcloud app deploy
  env:
  - '_DATABASE_URL=$_DATABASE_URL' 

- name: 'python'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      flask db upgrade

options:
  volumes:
    - name: 'pip-cache'
      path: '/root/.cache/pip'

